baseURL = "https://christin2200.github.io/blog"
languageCode = "en-us"
title = "christin2200"
theme = "zmd"
publishDir = "docs"
FootnoteReturnLinkContents = "â†©"
uglyurls = true
preserveTaxonomyNames = true
googleAnalytics = ""
disqusShortName = ""

[params]
  avatar = "Desktop/Github/blog/abouts/"
	anchor = true
	author = "christin2200"
